uztrack/track/urls.py
from classsettings.urls import url, Scope

from . import views


with Scope(regex=r'^track/', view=views, name='trackedway') as root:
    url('{}$', 'TrackedWayListView', name='{}-list')
    url('{}create/$', 'TrackedWayCreateView', name='{}-create')

    with Scope(regex=r'{}(?P<pk>\d+)/') as trackedway:
        url('{}$', 'TrackedWayDetailView', name='{}-detail')
        url('{}edit/$', 'TrackedWayEditView', name='{}-edit')

        with Scope(id=r'(?P<date>\d{4}-\d{2}-\d{2})') as history:
            url('{}{id}/$', 'TrackedWayHistoryDetailView', name='{}-history-detail')
            url('{}{id}/subscribe/$', 'HistorySubscriptionDetailView', name='history-subscription-detail')


urlpatterns = list(root.urls)

uztrack/track/models.py
import operator
from dateutil import rrule
from datetime import time

from django.db import models
from django.dispatch import Signal
from django.conf import settings
from django.contrib import admin, sites
from django.core import mail
from django.core.urlresolvers import reverse
from django.template.loader import render_to_string
from django.utils import timezone
from django.utils.functional import cached_property

from bitfield import BitField
from jsonfield import JSONField
from annoying.fields import AutoOneToOneField

from core.uzgovua import data
from core.utils import total_seconds
from . import utils


class Way(models.Model):
    """
    Defines abstract directed way between two train stations.
    """
    class Meta:
        unique_together = (('station_id_from', 'station_id_to'),)

    station_id_from = models.IntegerField()
    station_from = models.CharField(max_length=30)
    station_id_to = models.IntegerField()
    station_to = models.CharField(max_length=30)

    def __unicode__(self):
        return u'%s - %s' % (self.station_from, self.station_to)


class TrackedWay(models.Model):
    """
    Says that particular way should be checked for tickets on given departure weekdays.
    """
    way = models.ForeignKey(Way)
    days = BitField(flags=utils.WEEKDAYS.keys())
    owner = models.ForeignKey(settings.AUTH_USER_MODEL)
    departure_date = models.DateField(null=True, blank=True)
    dep_min_time = models.TimeField(null=True, blank=True, verbose_name=u'departure min time')
    dep_max_time = models.TimeField(null=True, blank=True, verbose_name=u'departure max time')
    arr_min_time = models.TimeField(null=True, blank=True, verbose_name=u'arrival min time')
    arr_max_time = models.TimeField(null=True, blank=True, verbose_name=u'arrival max time')

    def __unicode__(self):
        return self.way.__unicode__()

    @property
    def is_repeated(self):
        return self.departure_date is None

    @property
    def active_histories(self):
        """
        Returns collection of closest :class:`History` objects for a given way.
        Creates new records if needed.
        """
        from .models import TrackedWayDayHistory as History
        from .queries import get_search_till_date

        closest_dates = self.next_dates(get_search_till_date())

        if self.is_repeated:
            found_histories = History.objects.filter(departure_date__in=closest_dates)
            found_dates = found_histories.values_list('departure_date', flat=True)
            not_found_dates = filter(lambda d: d not in found_dates, closest_dates)
            histories_list = list(found_histories)
            histories_list.extend(self.histories.create(departure_date=date)
                                  for date in not_found_dates)
            return histories_list
        else:
            histories = self.histories.all()[:1]
            return [] if histories[0].active is False else histories

    def get_absolute_url(self):
        return reverse('trackedway-detail', kwargs=dict(pk=self.pk))

    def get_edit_url(self):
        return reverse('trackedway-edit', kwargs=dict(pk=self.pk))

    def get_delete_url(self):
        return '#'

    def next_dates(self, till):
        """
        Returns list of next arrival dates, starting from now.

        :param till: :class:`datetime.date` object, specified upper limit
        :return: list of :class:`datetime.date` objects
        """
        starts_from = timezone.now()

        if self.is_repeated:
            dateutil_weekdays = map(utils.get_dateutil_weekday, self.selected_weekdays)
            rule = rrule.rrule(rrule.WEEKLY, byweekday=dateutil_weekdays, until=till)
            return [x.date() for x in rule]
        else:
            is_expired = starts_from.date() > self.departure_date
            return [] if is_expired else [self.departure_date]

    @property
    def selected_weekdays(self):
        """
        Returns days it should check tickets on.
        Makes sense for repeated t-ways only.

        :return: generator of weekday names, like ('Monday', 'Friday', ...)
        """
        return (wday for wday, is_set in self.days if is_set)

    def save(self, is_critical=None):
        created = self.pk is None
        super(TrackedWay, self).save()

        if not self.is_repeated:
            kwargs = dict(departure_date=self.departure_date)
            kwargs.update(is_critical=True) if is_critical else None
            self.histories.create(**kwargs)

        if created and settings.POLLER_AUTOSTART_NEW:
            import poller.tasks
            poller.tasks.startup_tracked_way.delay(self.id)


class TrackedWayDayHistory(models.Model):
    """
    Describes tickets history for a given :class:`TrackedWay` way for a given day

    Field ``places_appeared`` points to :class:`TrackedWayDayHistorySnapshot`
    snapshot, when tickets were been found for the first time.
    Field ``places_disappeared`` points to :class:`TrackedWayDayHistorySnapshot`
    snapshot, when tickets were not been found for the first time.
    """
    class Meta:
        ordering = ['departure_date']
        verbose_name = u'tracked way history'
        verbose_name_plural = u'tracked way histories'
        unique_together = (('tracked_way', 'departure_date'))
    
    ABSOLUTE_URL_DATE_FORMAT = '%Y-%m-%d'

    active = models.BooleanField(default=True)
    tracked_way = models.ForeignKey(TrackedWay, related_name='histories')
    departure_date = models.DateField()
    is_critical = models.BooleanField(default=False)
    places_appeared = models.OneToOneField('track.TrackedWayDayHistorySnapshot',
                                            related_name='marks_appear', null=True)
    places_disappeared = models.OneToOneField('track.TrackedWayDayHistorySnapshot',
                                               related_name='marks_disappear', null=True)

    on_places_appeared = Signal()
    on_places_disappeared = Signal()

    def __unicode__(self):
        return u'%s on %s' % (self.tracked_way, self.departure_date)

    def get_url_kwargs(self):
        date = self.departure_date.strftime(self.ABSOLUTE_URL_DATE_FORMAT)
        return dict(pk=self.tracked_way_id, date=date)

    def get_absolute_url(self):
        return reverse('trackedway-history-detail',
                        kwargs=self.get_url_kwargs())

    def get_subscription_url(self):
        return reverse('history-subscription-detail',
                        kwargs=self.get_url_kwargs())

    @property
    def relevance(self):
        # TODO: remove and move to client
        elapsed = timezone.now() - self.last_snapshot.made_on
        elapsed_percentage = (total_seconds(elapsed) * 100 /
                              total_seconds(settings.POLLER_INTERVAL))
        return (elapsed, elapsed_percentage)

    @cached_property
    def last_snapshot(self):
        return self.snapshots.latest()

    @property
    def has_seats(self):
        return self.last_snapshot.total_places_count > 0

    @property
    def days_left(self):
        today =  timezone.datetime.today().date()
        return (self.departure_date - today).days

    def check_snapshot(self, snapshot):
        """
        Checks that places for current way history were appeared or disappeared
        within given snapshot.
        """
        if self.places_appeared is None:
            if snapshot.total_places_count > 0:
                self.subscription.notify_places_appeared(snapshot)
                self.places_appeared = snapshot
                self.save()
                self.on_places_appeared.send(sender=self)
        elif self.places_disappeared is None:
            if snapshot.total_places_count == 0:
                self.subscription.notify_places_disappeared(snapshot)
                self.places_disappeared = snapshot
                self.save()
                self.on_places_disappeared.send(sender=self)
        else:
            # Regular snapshot
            pass


class HistorySubscription(models.Model):
    class Meta:
        verbose_name = u'history subscription'

    DEFAULT_SUBJECT = 'Subscription update'
    CRITICAL_PREFIX = '[CRITICAL]'
    DEFAULT_TEMPLATE = 'email/subscription'

    enabled = models.BooleanField(default=False)
    history = AutoOneToOneField(TrackedWayDayHistory, related_name='subscription')

    @property
    def target_user(self):
        return self.history.tracked_way.owner

    def get_absolute_url(self):
        return self.history.get_subscription_url()

    def _notify(self, context, subject=None, template=None):
        if self.enabled:
            prefix = settings.EMAIL_SUBJECT_PREFIX
            prefix += self.CRITICAL_PREFIX if self.history.is_critical else ''
            subject = '%s %s' % (prefix, subject or self.DEFAULT_SUBJECT)
            from_email = settings.EMAIL_HOST_USER
            to_email = self.target_user.email
            context.update(subscription=self, history=self.history,
                           tracked_way=self.history.tracked_way,
                           SITE=sites.models.Site.objects.get_current().domain)
            template = template or self.DEFAULT_TEMPLATE
            text_content = render_to_string(template + '.txt', context)
            html_content = render_to_string(template + '.html', context)

            message = mail.EmailMultiAlternatives(subject, text_content,
                                                  from_email, [to_email])
            message.attach_alternative(html_content, 'text/html')
            message.send()

    def notify_places_appeared(self, snapshot):
        context = {    
            'title': '%d new tickets appeared' % snapshot.total_places_count,            
        }
        self._notify(context, template='email/places_appeared')

    def notify_places_disappeared(self, snapshot):
        self._notify({
            'title': 'Tickets for your subscription just have run out',
        })

uztrack/track/forms.py
import operator
from functools import partial
from itertools import izip

from django import forms

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit

from core.uzgovua.api import Api
from core.forms import SubmitFormMixin
from . import models, queries


class TrackedWayCreateForm(forms.ModelForm):
    class Meta:
        model = models.TrackedWay
        exclude = ('owner',)

    is_regular = forms.BooleanField(required=False)
    is_critical = forms.BooleanField(required=False)
    station_name_from = forms.CharField(min_length=2)
    station_name_to = forms.CharField(min_length=2)
    way = forms.Field(widget=forms.HiddenInput(), required=False)

    def __init__(self, *args, **kwargs):
        super(TrackedWayCreateForm, self).__init__(*args, **kwargs)
        self.fields.keyOrder.remove('way')
        self.fields.keyOrder.append('way')

    def clean_way(self):
        if 'station_name_from' in self.cleaned_data and \
           'station_name_to' in self.cleaned_data:
            way = queries.get_way(self.cleaned_data['station_name_from'],
                                  self.cleaned_data['station_name_to'])
            if way is None:
                raise forms.ValidationError('No such way')

            return way

        raise forms.ValidationError('Way is not specified')

    def clean(self):
        cleaned_data = super(TrackedWayCreateForm, self).clean()

        if cleaned_data['is_regular']:
            if cleaned_data['days'] == 0:
                self._errors['days'] = \
                    self.error_class(['At least one day should be specified'])
        else:
            if not cleaned_data['departure_date']:
                self._errors['departure_date'] = \
                    self.error_class(['Departure date is not specified'])        

        return cleaned_data

    def save(self, request):
        obj = super(TrackedWayCreateForm, self).save(commit=False)
        obj.owner = request.user
        single_day = not self.cleaned_data['is_regular']

        if single_day and self.cleaned_data['is_critical']:
            obj.save(is_critical=True)
        else:
            obj.save()

        return obj


class TrackedWayDetailForm(TrackedWayCreateForm):
    pass


class HistorySubscriptionForm(SubmitFormMixin, forms.ModelForm):
    class Meta:
        model = models.HistorySubscription
        exclude = ('history',)

uztrack/track/views.py
import json

from django.core.urlresolvers import reverse, reverse_lazy
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import get_object_or_404
from django.views.generic import TemplateView, ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView
from django.utils import timezone

from django_tables2 import SingleTableView
from braces.views import LoginRequiredMixin, AjaxResponseMixin, JSONResponseMixin

from core.utils import JsonResponse
from . import forms, models, tables
from .tables import WayTable, TrackedWayTable


class Home(TemplateView):
    template_name = 'home.html'


class TrackedWayCreateView(LoginRequiredMixin, CreateView):
    form_class = forms.TrackedWayCreateForm
    success_url = reverse_lazy('trackedway-list')
    template_name = 'track/trackedway_create.html'

    def form_valid(self, form):
        self.object = form.save(self.request)
        return JsonResponse({'redirect': self.get_success_url()})

    def form_invalid(self, form):
        return JsonResponse({'errors': form.errors})


class TrackedWayEditView(LoginRequiredMixin, UpdateView):
    model = models.TrackedWay
    form_class = forms.TrackedWayDetailForm


class TrackedWayDetailView(LoginRequiredMixin, DetailView):
    queryset = models.TrackedWay.objects.select_related('way')
    template_name = 'track/trackedway_detail.html'
    context_object_name = 'tracked_way'


class TrackedWayListView(LoginRequiredMixin, TemplateView):

    template_name = 'track/trackedway_list.html'

    def get_context_data(self, **kwargs):
        context = super(TrackedWayListView, self).get_context_data(**kwargs)

        tracked_ways = models.TrackedWay.objects.select_related('way')
        tables_data = {
            'repeated': filter(lambda way: way.is_repeated, tracked_ways),
            'nonrepeated': filter(lambda way: not way.is_repeated, tracked_ways)
        }
        for name in tables_data:
            table = tables.TrackedWayTable(tables_data[name])
            context['table_%s' % name] = table

        return context


class HistoryRelatedMixin(object):

    def get_object(self, queryset=None):
        date_format = models.TrackedWayDayHistory.ABSOLUTE_URL_DATE_FORMAT
        dt = timezone.datetime.strptime(self.kwargs['date'], date_format)
        return get_object_or_404(models.TrackedWayDayHistory,
                                 tracked_way_id=self.kwargs['pk'],
                                 departure_date=dt.date())


class TrackedWayHistoryDetailView(LoginRequiredMixin, HistoryRelatedMixin,
                                  DetailView):
    context_object_name = 'history'    
    model = models.TrackedWayDayHistory
    template_name = 'track/trackedway_history_detail.html'


class SubscriptionMixin(HistoryRelatedMixin):
    context_object_name = 'subscription'
    model = models.HistorySubscription
    form_class = forms.HistorySubscriptionForm

    def get_object(self, queryset=None):
        history = super(SubscriptionMixin, self).get_object(queryset)
        return history.subscription


class HistorySubscriptionDetailView(LoginRequiredMixin, SubscriptionMixin,
                                    AjaxResponseMixin,
                                    DetailView):
    template_name = 'track/history_subscription_detail.html'

    def post_ajax(self, request, **kwargs):
        form = forms.HistorySubscriptionForm(request.POST,
                                             instance=self.get_object())
        if form.is_valid():
            form.save()
            context = {'success': False}
        else:
            context = {'success': True, 'errors': form._errors}

        return HttpResponse(json.dumps(context))

uztrack/templates/track/base.html
{% extends 'base.html' %}

{% load static %}

{% block styles %}
  {{ block.super }}
  <link rel="stylesheet" type="text/css" href="{% static 'css/track.css' %}">
{% endblock %}

uztrack/templates/track/history_subscription_detail.html
{% extends 'track/base.html' %}

{% load staticfiles %}

{% block styles %}
  <link rel="stylesheet" href="{% static 'bootstrap-switch/dist/css/bootstrap3/bootstrap-switch.css' %}">
{% endblock %}

{% block scripts %}
  <script src="{% static 'bootstrap-switch/dist/js/bootstrap-switch.js' %}"></script>
  <script src="{% static 'js/history_subscription_detail.js' %}"></script>
{% endblock %}

{% block breadcrumbs %}
  {{ block.super }}
  {% with tracked_way=subscription.history.tracked_way %}
  <li><a href="{% url 'trackedway-list' %}">Tracked ways</a></li>
  <li><a href="{{ tracked_way.get_absolute_url }}">{{ tracked_way }}</a></li>
  <li><a href="{{ subscription.history.get_absolute_url }}">{{ subscription.history.departure_date }}</a></li>
  <li class="active">Subscription</li>
  {% endwith %}
{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-md-12">
      <form class="form-horizontal subscription">
        <p class="lead">Subscription settings:</p>
        <div id="div_id_enabled" class="form-group">
          <label for="id_enabled" class="col-sm-2 control-label">Enabled</label>
          <div class="controls col-sm-10">
            <input type="checkbox" id="id_enabled" {% if subscription.enabled %}checked{% endif %}>
          </div>
        </div>
        <div class="form-group">
        {% with email=subscription.history.tracked_way.owner.email %}
          <label class="col-sm-2 control-label">Email</label>
          <div class="col-sm-10">
            {% if email %}
            <input type="text" class="form-control" value="{{ subscription.history.tracked_way.owner.email }}" disabled>
            {% else %}
              <h5 class="text-danger">You should specify your email first</h5>
            {% endif %}
          </div>
        {% endwith %}
        </div>
      </form>
    </div>    
  </div>
{% endblock%}

uztrack/templates/track/trackedway_create.html
{% extends 'track/base.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block scripts %}
  {{ block.super }}
  <script src="{% static 'moment/moment.js' %}"></script>
  <script src="{% static 'select2/select2.js' %}"></script>
  <script src="{% static 'angular/angular.js' %}"></script>
  <script src="{% static 'eonasdan-bootstrap-datetimepicker/src/js/bootstrap-datetimepicker.js' %}"></script>  
  <script src="{% static 'angular-rangeslider/angular.rangeSlider.js' %}"></script>
  <script src="{% static 'angular-ui-select2/src/select2.js' %}"></script>
  <script src="{% static 'js/trackedway_create.js' %}"></script>
{% endblock %}

{% block styles %}
  {{ block.super }}
  <link rel="stylesheet" href="{% static 'angular-rangeslider/angular.rangeSlider.css' %}">
  <link rel="stylesheet" href="{% static 'select2/select2.css' %}">
  <link rel="stylesheet" href="{% static 'select2-bootstrap-css/select2-bootstrap.css' %}">
  <link rel="stylesheet" href="{% static 'css/trackedway_create.css' %}">
  <link rel="stylesheet" href="{% static 'eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.css' %}">
{% endblock %}
  
{% block content %}
  {% verbatim %}
  <div ng-app="TrackedWayApp" ng-controller="CreateCtrl" class="row">
    <div class="col-md-5 col-md-offset-3">
      <form name="form" method="post" ng-submit="submit()">
        <input type="hidden" ng-model="csrftoken" name="csrfmiddlewaretoken">

        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">Add new tracked way</h3>
          </div>
          <ul class="list-group">
            <li class="list-group-item">
              <div class="row">
                <div class="col-md-6">
                  <div class="form-group" ng-class="{'has-error': form.station_from.$error.required}">
                    <label class="control-label">Station from</label>
                    <div class="controls">
                      <input class="select2-input select2-default station-select" type="hidden"
                       ui-select2="stationFromSelectOptions" ng-model="station_from" name="station_from" required />
                      <span class="help-block" ng-show="form.station_from.$error.required">This field is required</span>
                    </div>
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group" ng-class="{'has-error': form.station_to.$error.required}">
                    <label class="control-label">Station to</label>
                    <div class="controls">
                      <input class="select2-input select2-default station-select" type="hidden"
                       ui-select2="stationToSelectOptions" ng-model="station_to" name="station_to" required />
                       <span class="help-block" ng-show="form.station_to.$error.required">This field is required</span>
                    </div>
                  </div>
                </div>
              </div>
            </li>

            <li class="list-group-item">
              <label class="control-label">Should I check it periodically?</label>
              <div class="row">
                <div class="col-md-12">
                  <div class="btn-group btn-group-justified">
                    <label class="btn btn-default" ng-class="{active: is_regular}">
                      <input type="radio" ng-model="is_regular" ng-value="true" />Yes
                    </label>
                    <label class="btn btn-default" ng-class="{active: !is_regular}">
                      <input type="radio" ng-model="is_regular" ng-value="false" />No
                    </label>
                  </div>
                </div>
              </div>
            </li>

            <li class="list-group-item" ng-show="is_regular">              
              <div class="row">                
                <div class="col-md-12 form-group"
                 ng-class="{'has-error': getSelectedDays() == 0}">
                  <label class="control-label">Select week days i should check tickets on</label>
                  <div class="btn-group btn-group-justified">
                    <label class="checkbox-inline btn btn-default" ng-repeat="day in days"
                     ng-class="day.enabled?'btn-success':'btn-default'">
                      <input type="checkbox" ng-model="days[$index].enabled" />
                      {{ day.title }}
                    </label>
                  </div>
                </div>
              </div>
            </li>
            <li class="list-group-item" ng-show="!is_regular">
              <div class="form-horizontal">
                <div class="form-group" ng-class="{'has-error': !departure_date}">
                  <label class="control-label col-md-6">Select departure date</label>
                  <div class="col-md-6">
                    <div class="input-group date" data-date-format="MMM Do" my-datepicker>
                      <p ng-show="form.departure_date.$error.required">Error</p>
                      <input type="text" class="form-control" name="departure_date"
                       ng-required="!is_regular" />
                      <span class="input-group-addon">
                        <span class="glyphicon glyphicon-calendar"></span>
                      </span>
                    </div>
                  </div>
                </div>
                <div class="form-group">
                  <label class="control-label col-md-6">Critical mode</label>
                  <div class="col-md-6">
                    <div class="btn-group btn-group-justified">
                      <label class="btn btn-default" ng-class="{active: is_critical}">
                        <input type="radio" ng-model="is_critical" ng-value="true" />Yes
                      </label>
                      <label class="btn btn-default" ng-class="{active: !is_critical}">
                        <input type="radio" ng-model="is_critical" ng-value="false" />No
                      </label>
                    </div>
                  </div>
                </div>
              </div>
            </li>

            <li class="list-group-item">
              <label class="control-label">Departure time</label>
              <div class="form-group">
                <div range-slider min="0" max="24" filter="hours" prevent-equal-min-max
                 model-min="dep_min_time" model-max="dep_max_time"></div>
              </div>
              <label class="control-label">Arrival time</label>
              <div class="form-group">
                <div range-slider min="0" max="24" filter="hours" prevent-equal-min-max
                 model-min="arr_min_time" model-max="arr_max_time"></div>
              </div>
            </li>

            <li class="list-group-item">
              <div class="form-actions">
                <input type="submit" id="submit-id-submit" class="btn btn-primary btn-block"
                 ng-disabled="!isValid()" />
              </div>
            </li>
          </ul>
        </div>
      </form>
    </div>
  </div>
  {% endverbatim %}
{% endblock %}

uztrack/templates/track/trackedway_form.html
{% extends 'track/base.html' %}

{% load crispy_forms_tags %}

{% block content %}
  <div class="row">
    <div class="col-md-4 col-md-offset-4">
      <h3>Edit tracked way</h3>
      {% crispy form %}
    </div>
  </div>
{% endblock %}

uztrack/templates/track/trackedway_history_detail.html
{% extends 'track/base.html' %}

{% block scripts %}
  {{ block.super }}
  <script>
    myApp.constant('urls', {
      histories: "{% url 'api-histories-list' %}",
      snapshots: "{% url 'api-snapshots-list' %}",
    });
  </script>
{% endblock %}

{% block breadcrumbs %}
  {{ block.super }}
  <li><a href="{% url 'trackedway-list' %}">Tracked ways</a></li>
  <li><a href="{{ history.tracked_way.get_absolute_url }}">{{ history.tracked_way }}</a></li>
  <li class="active">{{ history.departure_date }}</li>
  <li><a href="{{ history.get_subscription_url }}">Subscription</a></li>
{% endblock %}

{% block content %}
  DETAILS
{% endblock %}

uztrack/templates/track/trackedway_list.html
{% extends 'track/base.html' %}

{% load render_table from django_tables2 %}

{% block page_title %}List of regitered tracked ways{% endblock %}

{% block breadcrumbs %}
  {{ block.super }}
  <li><a href="">Tracked ways</a></li>
{% endblock %}

{% block content %}
  <p class="lead">Repeated tracked ways</p>
  {% render_table table_repeated %}
  <p class="lead">Specific tracked ways</p>
  {% render_table table_nonrepeated %}
  <a class="btn btn-success" href="{% url 'trackedway-create' %}">Create new</a>
{% endblock %}

uztrack/templates/track/way_create.html
{% extends 'track/base.html' %}

{% load crispy_forms_tags %}

{% block content %}
  <div class="row">
    <div class="col-md-4 col-md-offset-4">
      <h3>Add new way</h3>
      {% crispy form %}
    </div>
  </div>
{% endblock %}

uztrack/templates/track/way_form.html
{% extends 'track/base.html' %}

{% load crispy_forms_tags %}

{% block breadcrumbs %}
  {{ block.super }}
  <li><a href="{% url 'way-list' %}">Registered ways</a></li>
  <li class="active">{{ way }}</li>
{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-md-4 col-md-offset-4">
      <h3>Edit way "{{ way }}"</h3>
      {% crispy form %}
    </div>
  </div>
{% endblock %}

uztrack/templates/track/way_list.html
{% extends 'track/base.html' %}
{% load render_table from django_tables2 %}

{% block page_title %}List of regitered ways{% endblock %}

{% block breadcrumbs %}
  {{ block.super }}
  <li class="active">Registered ways</li>
{% endblock %}

{% block content %}
  {% render_table table %}
  <a class="btn btn-success" href="{% url 'trackedway-create' %}">Create new</a>
{% endblock %}